Repository getredash/website, pull requests merged in 2018-12, with the labels that each got.

#148 Remove links to Slack channel
  website/_data/footer_links.yml
  website/_includes/header.html
  website/contact.html
Labels: review

#149 Cleaned up grammar. Added info about using Markdown in text boxes
  website/_kb/user-guide/dashboards/dashboard-editing.md
Labels: Documentation, review

#151 Update profile pictures page
  website/_kb/user-guide/users/profile-pictures.md
Labels: Documentation, review

#153 Fix scrolling position of KB headers
  website/_assets/stylesheets/_components/_kb.scss
  website/_assets/stylesheets/_components/_section.scss
Labels: review

#155 Run Aloglia index only on production builds
  bin/build
Labels: review

#128 Alerts Documentation + PagerDuty
  website/_assets/images/docs/alerts/alert_destinations_1.png
  website/_assets/images/docs/alerts/alert_destinations_2.png
  website/_assets/images/docs/alerts/alert_destinations_3.png
  website/_assets/images/docs/alerts/alerts-selection.gif
  website/_assets/images/docs/alerts/pagerduty-key-location.png
  website/_assets/images/docs/alerts/pd_destination.png
  website/_kb/user-guide/alerts/creating-new-alert-destination.md
  website/_kb/user-guide/alerts/pagerduty-alert-destination.md
Labels: Documentation, review

#158 Added tagging and favorites page.
  website/_assets/images/docs/gitbook/favorites-example.png
  website/_assets/images/docs/gitbook/tagging-example.png
  website/_kb/user-guide/querying/favorites-tagging.md
Labels: in progress, review
