Repository getredash/website, pull requests merged in 2019-03, with the labels that each got.

#211 New json data source
  src/pages/kb/data-sources/querying-urls.md
  src/pages/kb/user-guide/visualizations/table-visualizations.md
  static/assets/images/docs/gitbook/json_field_select.png
  static/assets/images/docs/gitbook/json_list_of_objects.png
  static/assets/images/docs/gitbook/json_single_object.png
Labels: PR: unreviewed, in progress

#189 Added details about cohort visualization
  src/pages/kb/user-guide/visualizations/cohort-howto.md
  src/pages/kb/user-guide/visualizations/visualization-types.md
Labels: PR: merged

#219 Log pageview event on route change
  gatsby-browser.js
Labels: in progress

#220 Removed legacy scrollTo code
  gatsby-browser.js
Labels: in progress

#224 Ranbena suggested changes
  src/pages/kb/open-source/dev-guide/end-to-end-tests.md
Labels: in progress

#223 Add E2E Tests doc page
  src/pages/kb/open-source/dev-guide.md
  src/pages/kb/open-source/dev-guide/end-to-end-tests.md
Labels: in progress

#222 Fixed Help dropdown clickable area
  src/components/Header.jsx
Labels: in progress

#225 Added Salesforce to the integrations page.
  src/pages/data_sources/_integrations/salesforce.md
  static/assets/images/integrations/salesforce.png
Labels: in progress
