Repository getredash/website, pull requests merged in 2019-02, with the labels that each got.

#182 Updates to the dashboard sharing page.
  src/pages/kb/user-guide/dashboards/sharing-dashboards.md
  static/assets/images/docs/gitbook/full_screen_button.png
Labels: PR: unreviewed, in progress

#181 Updates to the query results data source page.
  src/pages/kb/user-guide/querying/query-results-data-source.md
Labels: PR: unreviewed, in progress

#190 Removed Zsolt's social info from about page.
  src/pages/about/index.jsx
Labels: PR: unreviewed, in progress

#191 Fixed a word. Changed date formats to ISO8601.
  src/pages/kb/user-guide/visualizations/cohort-howto.md
Labels: PR: unreviewed, in progress

#192 add some info on how to do remote debugging with Visual Studio Code
  src/pages/kb/open-source/dev-guide.md
  src/pages/kb/open-source/dev-guide/debugging.md
  src/pages/kb/open-source/dev-guide/docker.md
Labels: PR: reviewed-approved, in progress

#194 Fix twitter link in ContributorCard
  src/components/ContributorCard.jsx
Labels: PR: unreviewed, in progress

#193 Added team member Ranbena
  src/components/ContributorCard.jsx
  src/pages/about/index.jsx
  src/scss/_components/_page-about.scss
  static/assets/images/contributors/ranbena.jpg
Labels: PR: unreviewed, in progress

#196 Link to MongoDB documentation is broken
  src/pages/kb/data-sources/querying-mongodb.md
Labels: PR: unreviewed, in progress

#195 Query Parameter documentation updates
  src/pages/kb/user-guide/querying/query-parameters.md
  static/assets/images/docs/gitbook/dashboard_parameter_mapping.png
Labels: PR: unreviewed, in progress

#197 Implement drawer mode 😎
  gatsby-config.js
  src/scss/_components/_kb.scss
  src/scss/_components/_typography.scss
  src/scss/_partials/_footer.scss
  src/scss/_partials/_navbar.scss
  src/templates/HelpArticle.jsx
Labels: PR: unreviewed, in progress

#200 Dynamic setting “drawer” mode
  src/templates/HelpArticle.jsx
Labels: PR: unreviewed, in progress

#198 Updated dashboard sharing image and text
  src/pages/kb/user-guide/dashboards/sharing-dashboards.md
  static/assets/images/docs/gitbook/turn-on-url-sharing.gif
Labels: PR: unreviewed

#202 Remove current page title from breadcrumbs
  src/templates/HelpArticle.jsx
Labels: PR: reviewed-approved, in progress

#201 Simplified drawer method
  src/components/hoc/withIframeHook.jsx
  src/pages/help/index.jsx
  src/templates/HelpArticle.jsx
Labels: PR: unreviewed, in progress

#204 Minor updates to the writing a query page
  src/pages/kb/user-guide/dashboards/dashboard-editing.md
  src/pages/kb/user-guide/querying/writing-queries.md
  static/assets/images/docs/gitbook/experimental-owners-support.png
  static/assets/images/docs/gitbook/experimental-permissions-button.png
Labels: PR: unreviewed, in progress

#206 Fixed typo
  src/components/SectionGetStarted.jsx
Labels: PR: unreviewed, in progress

#203 Query Parameters updates
  src/pages/kb/user-guide/querying/query-parameters.md
  static/assets/images/docs/gitbook/query-parameter-modalv6.png
Labels: PR: unreviewed, in progress

#207 Added Jesse to the contributor page.
  src/pages/about/index.jsx
  static/assets/images/contributors/susodapop.jpg
Labels: PR: unreviewed, in progress

#208 Contributor card layout fixes
  src/scss/_components/_page-about.scss
  src/scss/_components/_section.scss
Labels: PR: reviewed-approved, in progress

#209 Slack auth failure/success pages
  src/pages/slack_failure/index.jsx
  src/pages/slack_success/index.jsx
Labels: PR: unreviewed

#205 Added documentation for table visualization options
  src/pages/kb/user-guide/visualizations/table-visualizations.md
  static/assets/images/docs/gitbook/dashboard-with-images.png
  static/assets/images/docs/gitbook/table-viz-options.png
Labels: PR: unreviewed, in progress

#212 Added team member Gabriel
  src/pages/about/index.jsx
  static/assets/images/contributors/gabrieldutra.jpg
Labels: PR: reviewed-approved, in progress

#213 Fix Google OAuth title
  src/pages/kb/open-source/setup.md
Labels: PR: unreviewed, in progress
