Repository getredash/website, pull requests merged in 2019-01, with the labels that each got.

#162 Clarified GCE setup commands.
  website/_kb/open-source/setup.md
Labels: in progress

#150 Added data sources with query runners not shown in the docs already
  website/_kb/data-sources/supported-data-sources.md
Labels: Documentation, review

#164 Add Rockset to list of databases
  website/_assets/images/integrations/rockset.png
  website/_data_sources/rockset.html
Labels: in progress, review

#176 Always stick footer to the bottom
  src/components/Layout.jsx
  src/scss/_components/_globals.scss
  src/scss/_components/_typography.scss
Labels: in progress, review

#177 Fix: policy page lead paragraph didn't have the class applied
  src/pages/text_pages/privacy.md
Labels: in progress, review

#178 Fix: sort articles in KB by order if available
  src/components/ArticlesList.jsx
  src/pages/help/index.jsx
Labels: in progress, review

#186 Fix: Top menu link to the forum doesn't work
  src/components/Header.jsx
Labels: PR: unreviewed, in progress

#188 Surround env vars names with backticks to proper render it with markdown
  src/pages/kb/open-source/admin-guide/env-vars-settings.md
Labels: PR: unreviewed, in progress
